services:
  products-search:
    build:
      context: .
    container_name: products-search-service
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    volumes:
      - ./src:/app/src
    command: npm run dev
